# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       uthash

# >> macros
# << macros

Summary:    A hash table for C structures
Version:    1.9.4
Release:    1
Group:      System/Kernel
License:    BSD-style single-clause
Source0:    %{name}-%{version}.tar.bz2
Source100:  uthash.yaml

%description
Any C structure can be stored in a hash table using 
uthash. Just add a UT_hash_handle to the structure 
and choose one or more fields in your structure to 
act as the key. Then use these macros to store, 
retrieve or delete items from the hash table.


%package devel
Summary:    %{summary}
Group:      Development/Libraries

%description devel
Description: %{summary}

%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# Running tests.
cd tests
make
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
mkdir -p  $RPM_BUILD_ROOT/usr/include
cd src
cp utarray.h uthash.h utlist.h utstring.h $RPM_BUILD_ROOT/usr/include
# << install post


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/utarray.h
%{_includedir}/uthash.h
%{_includedir}/utlist.h
%{_includedir}/utstring.h
# << files devel
